# Generated by Django 5.0.6 on 2024-07-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
