# Generated by Django 5.0.6 on 2024-07-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_team', '0002_alter_teamnews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamnews',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
