# Generated by Django 5.0.6 on 2024-07-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_team', '0007_shopcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
